version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    networks:
      - tienda-network

  # Opcional: Servicio de base de datos PostgreSQL local
  # Descomenta si quieres usar una base de datos local en lugar de la remota
  # db:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=tienda_db
  #     - POSTGRES_USER=tienda_user
  #     - POSTGRES_PASSWORD=tienda_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - tienda-network

networks:
  tienda-network:
    driver: bridge

# volumes:
#   postgres_data: 